In [1]:
import numpy as np

In [17]:
a = [1, 2, 3]
print(a)
a.clear()
print(a)

[1, 2, 3]
[]


In [19]:
a = [1, 2, 3] # lista
a = np.array(a) # se convierte en arreglo
print(a)
a = a.tolist() # se convierte en lista
print(a)
a.clear() # se limpia la lista
print(a)

[1 2 3]
[1, 2, 3]
[]


In [41]:
a = [6, 7, 10] # lista
b = [3, 15, 14]
a, b

([6, 7, 10], [3, 15, 14])

In [42]:
np.gradient([a,b])

[array([[-3.,  8.,  4.],
        [-3.,  8.,  4.]]),
 array([[ 1. ,  2. ,  3. ],
        [12. ,  5.5, -1. ]])]

In [43]:
a = [60, 40] 
np.gradient(a)

array([-20., -20.])

In [3]:
a = []
a

[]

In [4]:
a.append(32)
a

[32]

In [5]:
a.append(55)
a

[32, 55]

In [6]:
a.clear()
a

[]

In [10]:
np.abs(-6+3)

3